### ISSUE TITLE
404 for snap link

### ISSUE THREAD

**Issue by elreydetoda** [app-outlet/app-outlet.github.io#4]
it appears that this projects snap link is no longer working, when I click on the link it gives me a 404.

![image](https://user-images.githubusercontent.com/10230166/75311746-c6c42900-5825-11ea-8227-5501ee21601b.png)

I also tried to search for this project in the snap store and couldn't find it. Do you go by a different name in the snap store?

**Comment by MessiasLima** [comment]
App outlet doesn't work properly when packaged in snaps because of the confinement system. We requested classic confinement for our app, but the snapcrafters do not provide this for snaps that install other snaps, or third party apps. You can see all the discussion here https://forum.snapcraft.io/t/classic-confinement-for-app-outlet/13495

**Comment by MessiasLima** [comment]
We need to update our site. I know. We already have a design done but I haven't started coding yet.

**Comment by elreydetoda** [comment]
cool, thanks for the context :slightly_smiling_face:
